version: '3.8'

services:
  # NATS JetStream
  nats:
    image: nats:2.10-alpine
    container_name: test-nats
    ports:
      - "4222:4222"   # Client connections
      - "6222:6222"   # Cluster connections
      - "8222:8222"   # HTTP monitoring
    volumes:
      - ./deploy/nats-server.conf:/etc/nats/nats-server.conf
      - nats-data:/data
    command: ["-c", "/etc/nats/nats-server.conf", "-m", "8222"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PostgreSQL for persistent storage
  postgres:
    image: postgres:16-alpine
    container_name: test-postgres
    environment:
      POSTGRES_DB: task_scheduler_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  # MongoDB for document storage
  mongodb:
    image: mongo:7
    container_name: test-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test_tasks
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 3s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: test-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  nats-data: