# Test Configuration
[test]
# Run integration tests
integration_tests = true

# Run e2e tests
e2e_tests = true

# Run performance tests
performance_tests = false

# Test environment
[test.environment]
postgres_url = "postgres://postgres:postgres@localhost:5432/task_scheduler_test"
mongodb_url = "mongodb://localhost:27017/task_scheduler_test"
nats_url = "nats://localhost:4222"

# Test timeouts
[test.timeouts]
unit_test = 30
integration_test = 60
e2e_test = 120
performance_test = 300
