apiVersion: taskscheduler.legacylands.io/v1alpha1
kind: Task
metadata:
  name: test-worker-consume
  namespace: task-scheduler
spec:
  method: "echo"
  args:
  - "Testing worker consumption"
  priority: 100
  timeoutSeconds: 60