# Task Manager Configuration

[server]
grpc_address = "0.0.0.0:50051"
metrics_address = "0.0.0.0:9000"
tls_enabled = false
# tls_cert_path = "/path/to/server.crt"
# tls_key_path = "/path/to/server.key"
# tls_ca_path = "/path/to/ca.crt"
max_concurrent_requests = 50000

[storage]
backend = "memory"  # Options: memory, postgresql
cache_size = 10000
# postgres_url = "postgres://user:password@localhost/taskdb"
# redis_url = "redis://localhost:6379"

[queue]
nats_url = "nats://localhost:4222"
jetstream_enabled = true
queue_prefix = "tasks"

[kubernetes]
namespace = "task-scheduler"
enabled = false
# kubeconfig_path = "/path/to/kubeconfig"

[observability]
tracing_enabled = true
otlp_endpoint = "http://localhost:4317"
service_name = "task-manager"
log_level = "info"
sampling_ratio = 1.0

[security]
auth_enabled = false
audit_enabled = false
rbac_enabled = false
# jwt_secret = "your-secret-key"
# token_expiry = "24h"