---
# NATS ConfigMap with proper JetStream configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: task-scheduler
data:
  nats.conf: |
    # NATS Server Configuration
    server_name: nats-server
    
    # Client port
    port: 4222
    
    # HTTP monitoring port
    http_port: 8222
    
    # JetStream configuration
    jetstream {
      store_dir: /data/jetstream
    }
    
    # Logging
    debug: false
    trace: false
    logtime: true
    
    # Connection limits
    max_connections: 10000
    max_subscriptions: 1000000
    max_payload: 8MB
    
    # Write deadline
    write_deadline: "10s"
    
    # Single node configuration
---
# NATS Deployment  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: task-scheduler
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.10-alpine
        command:
        - nats-server
        - -c
        - /etc/nats/nats.conf
        - -js  # Enable JetStream
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        volumeMounts:
        - name: config
          mountPath: /etc/nats
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: monitor
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: monitor
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: config
        configMap:
          name: nats-config
      - name: data
        emptyDir:
          sizeLimit: 2Gi  # Ensure this is larger than max_file
---
# NATS Service
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: task-scheduler
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
    protocol: TCP
  - name: monitor
    port: 8222
    targetPort: 8222
    protocol: TCP
  type: ClusterIP