---
# Task Operator Service
apiVersion: v1
kind: Service
metadata:
  name: task-operator
  namespace: task-scheduler
  labels:
    app: task-operator
    component: control-plane
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9002
    targetPort: 9002
    protocol: TCP
  selector:
    app: task-operator
---
# Task Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-operator
  namespace: task-scheduler
  labels:
    app: task-operator
    component: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-operator
  strategy:
    type: Recreate  # Only one operator should be active at a time
  template:
    metadata:
      labels:
        app: task-operator
        component: control-plane
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9002"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: task-operator
      containers:
      - name: task-operator
        image: task-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RUST_LOG
          value: "info,task_operator=debug"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: "nats://nats.task-scheduler.svc.cluster.local:4222"
        - name: OTLP_ENDPOINT
          value: "http://jaeger.task-scheduler.svc.cluster.local:4317"
        - name: TRACING_ENABLED
          value: "true"
        ports:
        - name: metrics
          containerPort: 9002
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
---
# Leader Election ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-operator-leader
  namespace: task-scheduler
data: {}
---
# PodDisruptionBudget for Task Operator
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: task-operator-pdb
  namespace: task-scheduler
spec:
  minAvailable: 0  # Allow operator to be disrupted during maintenance
  selector:
    matchLabels:
      app: task-operator