[package]
name = "data-transform-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
task-plugins = { path = "../../crates/task-plugins" }
async-trait = "0.1"
serde_json = "1.0"