version: '3.8'

services:
  grafana:
    image: grafana/grafana:11.1.0
    container_name: task-scheduler-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-dashboards-volume:/etc/grafana/provisioning/dashboards
      - grafana-datasources-volume:/etc/grafana/provisioning/datasources
    networks:
      - docker_task-scheduler-net
    depends_on:
      - prometheus

volumes:
  grafana-data:
    external: true
  grafana-dashboards-volume:
    external: true
  grafana-datasources-volume:
    external: true

networks:
  docker_task-scheduler-net:
    external: true
