[server]
grpc_address = "0.0.0.0:50051"
metrics_address = "0.0.0.0:9000"
tls_enabled = false
max_concurrent_requests = 100000
worker_threads = 16

[storage]
backend = "postgresql"
postgres_url = "postgres://task_scheduler:task_scheduler_pass@task-scheduler-postgres:5432/task_scheduler"
redis_url = "redis://task-scheduler-redis:6379"
cache_size = 10000
max_connections = 100
min_connections = 10
result_retention_seconds = 3600
cleanup_interval_seconds = 300
enable_binary_storage = true

[queue]
nats_url = "nats://task-scheduler-nats:4222"
jetstream_enabled = true
queue_prefix = "tasks"
batch_size = 2000
prefetch_count = 20000

[kubernetes]
namespace = "task-scheduler"
enabled = false

[observability]
tracing_enabled = false
otlp_endpoint = "http://task-scheduler-jaeger:4317"
service_name = "task-manager"
log_level = "info"
sampling_ratio = 0.01

[security]
auth_enabled = false
rbac_enabled = false
audit_enabled = false
audit_log_path = "/var/log/task-scheduler/audit.log"
audit_min_severity = "warn"
session_timeout = 3600