[package]
name = "plugin_example"
version = "0.1.0"
edition = "2021"

[lib]
name = "plugin_example"
crate-type = ["cdylib"]

[workspace]

[dependencies]
task-scheduler = { path = "../.." }
tokio = { version = "1.0", features = ["time"] }
