apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: task-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_USER
          value: taskscheduler
        - name: POSTGRES_PASSWORD
          value: taskscheduler
        - name: POSTGRES_DB
          value: taskscheduler
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: task-scheduler
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
